"""group_id nullable True

Revision ID: 119704212a48
Revises: af443da877ff
Create Date: 2024-08-22 14:44:09.886050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119704212a48'
down_revision = 'af443da877ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
