"""create num_of_groups

Revision ID: b989e6f884f4
Revises: 119704212a48
Create Date: 2024-08-27 11:20:02.941521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b989e6f884f4'
down_revision = '119704212a48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_of_groups', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('num_of_groups')

    # ### end Alembic commands ###
